version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: netpulse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: netpulse
      POSTGRES_USER: netpulse
      POSTGRES_PASSWORD: netpulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana:11.1.0
    container_name: netpulse-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  postgres_data:
